### ISSUE TITLE
Case Sensitive issues

### ISSUE THREAD

**Issue by Fantasmos** [TF2Maps/SteamBotLite#16]
Maps should warn users when not all lower-case, and !delete and similar commands are case sensitive as of right now, which isn't exactly good

**Comment by LaylConway** [comment]
Perhaps just .ToLower the map name instead?

**Comment by Fantasmos** [comment]
Might be best to ensure that users know that their map files can't contain upper cases though since how the server runs, I'm thinking to make the check .tolower() but force the input to not have upper cases
